# Numpy

NumPy is the fundamental package for scientific computing with Python. It contains among other things:

 - a powerful N-dimensional array object

 - sophisticated (broadcasting) functions

 - tools for integrating C/C++ and Fortran code

 - useful linear algebra, Fourier transform, and random number capabilities

Besides its obvious scientific uses, NumPy can also be used as an efficient multi-dimensional container of generic data. Arbitrary data-types can be defined. This allows NumPy to seamlessly and speedily integrate with a wide variety of databases.

NumPy is licensed under the [BSD](https://numpy.org/license.html#license) license, enabling reuse with few restrictions.

In [80]:
import numpy as np

# Create numpy array

## Create simple numpy array

There are multiple ways to create a numpy array. The most common way to create __*np.ndarray*__ object - create it from native __*list*__

In [81]:
native_list = [1,2,3,4,5,6,7]
numpy_array = np.array(native_list)
numpy_array

array([1, 2, 3, 4, 5, 6, 7])

In [82]:
type(numpy_array)

numpy.ndarray

__*np.ndarray*__ object has multiple properties. Let's explore some of them

In [83]:
print('shape:\t', numpy_array.shape)
print('dtype:\t', numpy_array.dtype)
print('size:\t', numpy_array.size)
print('data:\t', numpy_array.data)
print('ndim:\t', numpy_array.ndim)

shape:	 (7,)
dtype:	 int64
size:	 7
data:	 <memory at 0x7f94be8e5c80>
ndim:	 1


## Create zero array

Sometimes you need to create array for ruther working with it. For example, black image for drawing or matrix to count occurence of something, correlation matrix etc. You can use __*np.zero*__ for creating array. Each pixel will have value _0_.

In [84]:
zero_arr = np.zeros([300, 300, 3], dtype=np.float128)
np.unique(zero_arr)

array([0.], dtype=float128)

__*np.unique*__ is used for printing all unique values. So, array is completely zero. Nice.

## Create empty array

There are situatins when you must have created array for further filling with data. Note, that increasing array size is very slow operation becuase of realocation. Creating zero array isn't a good idea because it will fill all elements with _0_ value and it is just waste of the time.

In [ ]:
empty_arr = np.empty([999, 999, 20], dtype=np.float128)
np.unique(empty_arr)

array([0.e+0000, 4.e-4951], dtype=float128)

Most of the time __*np.empty*__ returns array with zero elements, but you __can't be shure__ about that. 

## Create multidimensional numpy array

In [ ]:
md_list = [[y/10 for y in range(7)] for x in range(5)]
md_np_array = np.array(md_list)
md_np_array

In [ ]:
print('shape:\t', md_np_array.shape)
print('dtype:\t', md_np_array.dtype)
print('size:\t', md_np_array.size)
print('data:\t', md_np_array.data)
print('ndim:\t', md_np_array.ndim)

## Creating array with meaningfull data

Numpy also provides functions for creating array with meaningfull values. __*np.linspace*__ returns num evenly spaced samples, calculated over the interval [start, stop].

In [ ]:
np.linspace(start=2, stop=8, num=6)

__*np.arage*__ generates values within the half-open interval [start, stop) (in other words, the interval including start but excluding stop). For integer arguments the function is equivalent to the Python built-in range function, but returns an ndarray rather than a list.

In [ ]:
np.arange(start=2, stop=8, step=2)

# Numpy reference

## Value referencing

Numpy is based on C-written backend. Python is just hight level API for data manipulation. When you assign array to another variable, you just __assign only reference__ to the data. Be careful.

In [ ]:
def modify(x):
    x[-1] = -88
    
arr = np.array([1,2,3,4,5])
arr_copy = arr
arr_copy[2] = -99
modify(arr_copy)
arr

# Numpy indexing

## Signle indexing

Numpy offers several ways to index into arrays.

In [ ]:
arr = np.array([[1, 2, 3],
                [3, 4, 5],
                [5, 6, 7]])
arr

Accessing by single index returns sub-array, i.e. all elements with first index equils to __0__

In [ ]:
arr[0]

Access single element in 2D array requires 2 indexes. You can specify them in different way, but the second approach is more convenient

In [ ]:
print('Elements in 3th row and 2nd column:', arr[2][1])
print('Elements in 3th row and 2nd column:', arr[2, 1])

## Numpy slicing

Slicing: Similar to Python lists, numpy arrays can be sliced. Since arrays may be multidimensional, you must specify a slice for each dimension of the array:

In [ ]:
arr[0:2]

But in numpy you can use multidimensional slicing

In [ ]:
arr[0:2, 1:3]

If you want to slice only 2nd dimension, you shouldn't specify full range for first axis, just specify __*:*__

In [ ]:
arr[:, 1:3]

<span style="color:red">Don't do something like this</span>

In [ ]:
arr[0:arr.shape[0], 1:3]

Note, that slicing works by refrence. If you modify sliced array, original array is moddified too.

In [ ]:
arr = np.array([[1,2,3], [3,4,5]])
arr[:, 0:2] = -99
arr

# Math in numpy

## Elementwise operations

In [ ]:
arr1 = np.array([1,2,3])
arr2 = np.array([3,2,1])

You can easily apply elementwise operations.

In [ ]:
print('Add:\t', arr1+arr2)
print('Sub:\t', arr1-arr2)
print('Mult:\t', arr1*arr2)
print('Div:\t', np.round(arr1/arr2, 2))
print('Cos:\t', np.round(np.cos(np.linspace(0, np.pi*4, 10)), 2))

## Clasic algebra operations

Classic vector/matrix operations are available too. Let's prepare matrix using some numpy magic.
__*np.tile*__ construct an array by repeating input array the N times

In [ ]:
arr2_3x = np.tile(arr2, 3)
arr2_3x

__*nparray.reshape*__ change the shape of source array to shape given by user

In [ ]:
matrix = arr2_3x.reshape(3,3)
matrix

Transpose matrix

Now we are ready to perform classic vector by matrix multiplication

In [ ]:
dot_result = np.dot(arr1, matrix)
dot_result

# Array merging, concationation, filtering and other kinds of magic

## Prepare random array

You can create random array in different ways. The simplest one - using __*np.random.uniform*__ for uniform distribution

In [ ]:
arr = np.random.uniform(low=-3, high=3, size=[10])
arr

But float numbers isn't so cool for example. You can convert array to integer type

In [ ]:
arr = arr.astype(np.int8)
arr

## Extract negative elements from array  

Numpy also supports elementwise comprasion

In [ ]:
arr < 0

At the same time numpy indexing support boolean mask

In [ ]:
arr[[True, True, False, False, False, False, False, False, False, True]]

Compile all together

In [ ]:
arr[arr < 0]

## Concatenate negative and positive elements together

You can concatenate arrays in one second using __*np.concatenate*__. Notice, array should have the same shape except in the dimension you want to concatenate. In other words, you cannot concatenate 2x2 matrix and 3x3 matrix (because of invalid result shape)

In [ ]:
arr1, arr2

In [ ]:
concated_res = np.concatenate((arr1, arr2), axis=0)
concated_res

Cancatenate negative and positive elements inline

In [ ]:
np.concatenate((arr[arr<0], arr[arr>0]), axis=0)

# Tasks

## Task 1: Create 1D numpy

\begin{pmatrix}2 & 3 & 4 & 5 & 6 & 7 & 8 & 9\end{pmatrix}

In [ ]:
###
### TODO: Write code here 
###

## Task 2: Create matrix

\begin{pmatrix}1 & 1 & 1 & 1 \\ 2 & 2 & 2 & 2 \\ 3 & 3 & 3 & 3\end{pmatrix}
Place result in __*result_array*__

In [ ]:
###
### TODO: Write code here:
###

# Task 3: 

You are given input matrix:
\begin{pmatrix}1 & 2 & 3 & 4 \\ 5 & 6 & 7 & 8 \\ 9 & 10 & 11 & 12 \\ 13 & 14 & 15 & 16\end{pmatrix}
Slice it and get this submatrix:
\begin{pmatrix}10 & 11 \\ 14 & 15\end{pmatrix}

In [ ]:
import itertools

def next_element():
    start_element = 1
    while True:
        yield start_element
        start_element += 1
        
input_matrix = np.array(list(itertools.islice(next_element(), 4*4))).reshape(4,4)

In [ ]:
###
### TODO: Write code here
###

# Task 4: Multiply matrices

Create two matrix and multiply them.
$$
\begin{pmatrix}
    1 & 1 & 1 \\
    1 & 1 & 1 \\
    1 & 1 & 1
\end{pmatrix}
.
\begin{pmatrix}
    2 & 2 & 2 \\
    2 & 2 & 2 \\
    2 & 2 & 2
\end{pmatrix}
=
\begin{pmatrix}
    6 & 6 & 6 \\
    6 & 6 & 6 \\
    6 & 6 & 6
\end{pmatrix}
$$

Tip: You can easily create zero array using __*np.zeros*__. E.g. __*np.zeros(shape=[3,4])*__ creates 3x4 matrix filled with _0_

In [ ]:
###
### TODO: Write code here
###

# Task 5: Manipulate with vectors

You are given two vectors:
\begin{pmatrix}
    1 & 0 & 1 & 2 & 1 & 2
\end{pmatrix}
\begin{pmatrix}
    2 & 1 & 2 & 1 & 0 & 1
\end{pmatrix}

Extract even elements from each vector and concatenate them.
Tip: Use elementwise __*%*__ operator

In [ ]:
vec1 = np.array([1, 0, 1, 2, 1, 2])
vec2 = vec1[::-1]

In [ ]:
###
### TODO: Write code here
###